### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by planath** [dev-kitchen/interactive-book-ios-prototype#18]
Alles nach Vorgabe von @pfischtr umsetzen.

**Comment by planath** [comment]
- [x] #21 TabBar
- [x] #22 ScanButton Transition
- [ ] #24 Chapter titles in Table
- [ ] #29 White Icon for retry @ scanner view
- [x] #30 Status bar color
- [ ] #32 Fading transition after welcome
